typography_spectrum: 0.8093448
color:
  saturation: 0.2601386033929884
  brandStrength: 0.7332706197630614
  rhythmicContrast: 0.4234684542752802
  lightness: 0.8958498588763177
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
github: true
layout_spectrum: 0.9500536
author:
  name: Adam Saltiel All Rights Reserved © Configuration Science Ltd
  email: adam.saltiel@gmail.com
  url: 'http://configurationscience.co.uk'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bffeee52-6d9f-4f52-b6c4-9d200d6451e8.png
name: The AAP
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/512dbea8-7601-4bda-8e98-a7ceed86e1b7.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: The Association of Arbours Psychotherapists
content: []
description: professional work of the association of arbours psychotherapists (AAP)
purpose:
  - type: internal
    label: Autumn Lecture 2017 & AAP AGM
    item: a022e596-d17c-4fc2-a36c-7b49b6e797ad
  - type: external
    label: Lecture Series
    url: 'http://aapmembers.org/lecture-series'
